#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MIN_NODE_MAJOR=20
MIN_PYTHON_MAJOR=3
MIN_PYTHON_MINOR=11

HOST_OVERRIDE=""
RUN_AFTER=0
SKIP_CHECKS=0
NO_APT=0
MARKER="Generated by scripts/setup-raspberry-pi.sh"

usage() {
  cat <<'USAGE'
Usage: bash scripts/setup-raspberry-pi.sh [options]

Bootstraps GuessRush on Raspberry Pi OS after cloning the repository.

Options:
  --host <ip-or-hostname>  Use this LAN host in generated .env files.
  --run                   Start the app after setup finishes.
  --skip-checks           Skip pytest, ruff, frontend lint/test/build.
  --no-apt                Do not install system packages with apt.
  -h, --help              Show this help.

Examples:
  bash scripts/setup-raspberry-pi.sh
  bash scripts/setup-raspberry-pi.sh --host 192.168.1.42 --run
  bash scripts/setup-raspberry-pi.sh --skip-checks
USAGE
}

log() {
  printf '\n[guessrush] %s\n' "$*"
}

warn() {
  printf '\n[guessrush:warn] %s\n' "$*" >&2
}

fail() {
  printf '\n[guessrush:error] %s\n' "$*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host)
      [ "${2:-}" ] || fail "--host requires an IP address or hostname"
      HOST_OVERRIDE="$2"
      shift 2
      ;;
    --run)
      RUN_AFTER=1
      shift
      ;;
    --skip-checks)
      SKIP_CHECKS=1
      shift
      ;;
    --no-apt)
      NO_APT=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
done

sudo_cmd() {
  if [ "$(id -u)" -eq 0 ]; then
    printf ''
  elif command -v sudo >/dev/null 2>&1; then
    printf 'sudo'
  else
    fail "sudo is required to install system packages. Install sudo or rerun with --no-apt after installing dependencies manually."
  fi
}

version_at_least() {
  local major="$1"
  local minor="$2"
  local required_major="$3"
  local required_minor="$4"

  if [ "$major" -gt "$required_major" ]; then
    return 0
  fi
  if [ "$major" -eq "$required_major" ] && [ "$minor" -ge "$required_minor" ]; then
    return 0
  fi
  return 1
}

detect_lan_host() {
  if [ -n "$HOST_OVERRIDE" ]; then
    printf '%s\n' "$HOST_OVERRIDE"
    return
  fi

  local detected=""
  if command -v hostname >/dev/null 2>&1; then
    detected="$(
      hostname -I 2>/dev/null |
        tr ' ' '\n' |
        grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' |
        grep -Ev '^(127|169\.254)\.' |
        head -n 1 || true
    )"
  fi

  if [ -z "$detected" ] && command -v ip >/dev/null 2>&1; then
    detected="$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p' | head -n 1 || true)"
  fi

  if [ -z "$detected" ]; then
    warn "Could not detect a LAN IP. Generated URLs will use localhost; pass --host <LAN_IP> for phone testing."
    detected="localhost"
  fi

  printf '%s\n' "$detected"
}

check_os() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    case "${ID:-}:${ID_LIKE:-}:${PRETTY_NAME:-}" in
      *raspbian* | *debian* | *Raspberry\ Pi*)
        log "Detected ${PRETTY_NAME:-Raspberry Pi OS compatible system}."
        ;;
      *)
        warn "This script is tuned for Raspberry Pi OS/Debian. Continuing on ${PRETTY_NAME:-unknown Linux}."
        ;;
    esac
  fi
}

install_apt_packages() {
  if [ "$NO_APT" -eq 1 ]; then
    log "Skipping apt package installation because --no-apt was provided."
    return
  fi

  command -v apt-get >/dev/null 2>&1 || fail "apt-get was not found. Install dependencies manually or use Raspberry Pi OS."

  local sudoer
  sudoer="$(sudo_cmd)"

  log "Installing required system packages with apt."
  if [ -n "$sudoer" ]; then
    $sudoer apt-get update
    $sudoer apt-get install -y ca-certificates curl gnupg git build-essential openssl python3 python3-dev python3-venv python3-pip
  else
    apt-get update
    apt-get install -y ca-certificates curl gnupg git build-essential openssl python3 python3-dev python3-venv python3-pip
  fi
}

find_python() {
  local candidate
  for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
      local version major minor
      version="$("$candidate" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || true)"
      major="${version%%.*}"
      minor="${version#*.}"
      if [ -n "$major" ] && [ -n "$minor" ] && version_at_least "$major" "$minor" "$MIN_PYTHON_MAJOR" "$MIN_PYTHON_MINOR"; then
        printf '%s\n' "$candidate"
        return
      fi
    fi
  done

  fail "Python ${MIN_PYTHON_MAJOR}.${MIN_PYTHON_MINOR}+ is required. Raspberry Pi OS Bookworm's python3 package is sufficient."
}

node_major() {
  if command -v node >/dev/null 2>&1; then
    node -p 'Number.parseInt(process.versions.node.split(".")[0], 10)' 2>/dev/null || printf '0'
  else
    printf '0'
  fi
}

install_node_if_needed() {
  local major
  major="$(node_major)"
  if [ "$major" -ge "$MIN_NODE_MAJOR" ] 2>/dev/null; then
    log "Node.js $(node --version) is already installed."
    return
  fi

  if [ "$NO_APT" -eq 1 ]; then
    fail "Node.js ${MIN_NODE_MAJOR}+ is required. Install Node.js manually, then rerun this script."
  fi

  command -v curl >/dev/null 2>&1 || fail "curl is required to install Node.js."
  command -v apt-get >/dev/null 2>&1 || fail "apt-get is required to install Node.js automatically."

  local sudoer
  sudoer="$(sudo_cmd)"

  log "Installing Node.js 22 from NodeSource because the current Node is missing or too old."
  if [ -n "$sudoer" ]; then
    curl -fsSL https://deb.nodesource.com/setup_22.x | $sudoer -E bash -
    $sudoer apt-get install -y nodejs
  else
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt-get install -y nodejs
  fi

  major="$(node_major)"
  [ "$major" -ge "$MIN_NODE_MAJOR" ] 2>/dev/null || fail "Node.js installation finished, but node --version is still below ${MIN_NODE_MAJOR}."
  command -v npm >/dev/null 2>&1 || fail "npm was not found after installing Node.js."
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif [ -r /proc/sys/kernel/random/uuid ]; then
    tr -d '-' </proc/sys/kernel/random/uuid
  else
    printf 'change-me-%s\n' "$(date +%s)"
  fi
}

write_env_file() {
  local path="$1"
  local content="$2"

  if [ -f "$path" ] && ! grep -q "$MARKER" "$path"; then
    warn "Keeping existing $path. Delete it or add the generated marker if you want this script to rewrite it."
    return
  fi

  printf '%s\n' "$content" >"$path"
  log "Wrote $path."
}

configure_env_files() {
  local lan_host public_url api_url app_secret
  lan_host="$(detect_lan_host)"
  public_url="http://${lan_host}:5173"
  api_url="http://${lan_host}:8000"
  app_secret="$(generate_secret)"

  write_env_file "backend/.env" "# ${MARKER}
BACKEND_DATABASE_URL=sqlite:///./guessrush.db
FRONTEND_ORIGIN=${public_url}
PUBLIC_APP_URL=${public_url}
APP_SECRET=${app_secret}
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,${public_url}"

  write_env_file "frontend/.env.local" "# ${MARKER}
VITE_API_BASE_URL=${api_url}
VITE_PUBLIC_APP_URL=${public_url}"

  log "LAN app URL: ${public_url}"
}

install_backend() {
  local python_bin="$1"

  log "Creating/updating backend virtual environment."
  "$python_bin" -m venv backend/.venv

  (
    cd backend
    # shellcheck disable=SC1091
    . .venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install -e ".[dev]"
    alembic upgrade head
  )
}

install_frontend() {
  command -v npm >/dev/null 2>&1 || fail "npm is required."

  log "Installing frontend dependencies."
  (
    cd frontend
    if [ -f package-lock.json ]; then
      npm ci
    else
      npm install
    fi
  )
}

run_checks() {
  if [ "$SKIP_CHECKS" -eq 1 ]; then
    log "Skipping validation checks because --skip-checks was provided."
    return
  fi

  log "Running backend checks."
  (
    cd backend
    # shellcheck disable=SC1091
    . .venv/bin/activate
    ruff check .
    pytest
  )

  log "Running frontend checks."
  (
    cd frontend
    npm run lint
    npm run test
    npm run build
  )
}

main() {
  [ -f frontend/package.json ] || fail "Run this script from the GuessRush repository root."
  [ -f backend/pyproject.toml ] || fail "Run this script from the GuessRush repository root."

  check_os
  install_apt_packages
  install_node_if_needed

  local python_bin
  python_bin="$(find_python)"
  log "Using $("$python_bin" --version) and Node.js $(node --version)."

  configure_env_files
  install_backend "$python_bin"
  install_frontend
  run_checks

  log "Setup complete."
  printf '%s\n' "Start the app with:"
  printf '%s\n' "  bash scripts/run-raspberry-pi.sh"
  printf '%s\n' "Then open the printed LAN URL from phones on the same Wi-Fi."

  if [ "$RUN_AFTER" -eq 1 ]; then
    exec bash scripts/run-raspberry-pi.sh
  fi
}

main "$@"
